### ISSUE TITLE
CommentsAbout is a too simplistic structure in \xsd\netex_part_5\part5_fm\netex_nm_individualTraveller_version.xsd

### ISSUE THREAD

**Issue by ue71603** [NeTEx-CEN/NeTEx#318]
CommentsAbout is a single MultilingualString

In this place a full Comments-Structure needs to be established, if this is something to use.

We need: 
* DateTime
* Stars
* UserAcronym
* Text
https://www.amazon.com/Data-Structures-Algorithms-Java-2nd/product-reviews/0672324539

**Comment by ue71603** [comment]
There is no Comment Structure in Transmodel. Probably not needed, it you think it does @Aurige  please add a CR otherwise delete the Transmodel label.

**Comment by Aurige** [comment]
Yes that's something we can improve, but I agree that these details may not be of interest at Transmodel level (however we still can mention it to the group, since it cannot be only our on choice)
With **UserAcronym**, you want the to identify the User who did the comment, right ? Same for **stars** but then we also need a multi-comment management (for now it is a global Raking/Comment)

**Comment by Aurige** [comment]
see https://github.com/NeTEx-CEN/NeTEx/pull/519
