### ISSUE TITLE
Facility extended with AvailabilityCondition

### ISSUE THREAD

**Issue by ue71603** [NeTEx-CEN/NeTEx#470]
* ServiceJourney should allow for facilities with Facilities and an AvailabilityConditionRef
* Call should allow for the same.

Either show how to do it correctly (dfifferently) or add this feature to ServiceJourney and Call

Discuss proposal with David and Laurent.

**Comment by ue71603** [comment]
Stefan: needs to be denomalized in search (to ServiceJourney). We need to tell journey planners. Not against it.
@duexw : What do you think?

**Comment by ue71603** [comment]
Stefan: In the case of the equipment. Is it no longer present. The slippery slope would be validity to ServicePattern

**Comment by Aurige** [comment]
I agree that AvailabilityCondition can be very useful for Facilities, but I would not limit this to ServiceJourney and Call. If we go in that direction, we also need it for all Site, etc.
This said, it is tricky to add AvailabilityConditions in an elegant and backward compatible way ... we need to think about it

By the way, different but connected topic, I very recently looked for an AC (Air Conditioning) facility and didn't find any ! Did I miss something ?

**Comment by ue71603** [comment]
I think we need AC

**Comment by skinkie** [comment]
We might need a complete new enumeration for that.

**Comment by Aurige** [comment]
In fact **AvailabilityCondition** are already there for facilities:

We are using a "**facilities**" wrapper:
![image](https://github.com/NeTEx-CEN/NeTEx/assets/3328999/e31104cf-40af-42d0-b6d5-44d652c007e3)

It can contain several **ServiceFacilitySet** and each already have **ValidityCondition** that can be an **AvailabilityContition** thanks to the **ValidityCondition_** substitution group. 
![image](https://github.com/NeTEx-CEN/NeTEx/assets/3328999/ba94ed03-7d63-42bb-912b-746c119feab0)

So you jut need to group together the facilities having the same validity.

**Comment by ue71603** [comment]
I add also @skinkie  @klement-MENTZ  to the discussion.
@Aurige  Thanks for the first answer. However,  we still have two issues.

**ServiceFacilitySet in Call or CallPart**
* For ServiceJourney this may work
* There is no ServiceFacilitySet in Call (or CallPart). Do you think we could add the structure there as well?  Or do you think that a ServiceFacilitySet can only exist on a ServiceJourneyPart?

**FacilityAssignment (different handling of AvailabilityCondition=**
We have a huge number of ServiceFacilitySets.
If we would see it as a bundle, and because the AvailabilityCondition is there. We need a ServiceFacilitySet for each possible AvailabilityCondition (for the whole timetable). This results in 10000 ServiceFacilitySets with the same three Facilities and different AvailabiltyConditions.
Couldn't it be possible to have in facilities/  a combination of a ServiceFacilitySet and an AvailabilityCondition? Especially when only the ServiceFacilitySetRef would be used.  Or is this the way to go?

So something along these lines would be intended:
<facilities>
<FacilityAssignment id="ch:1:facility:f2" version="any" order="1">
      <validityConditions>
            <AvailabilityConditionRef ref="ch:1:AvailabilityCondition:b7" version="any"/>
      </validityConditions>
      <ServiceFacilitySetRef ref="ch:1:ServiceFacilitySet:A___B" version="any"/>
</FacilityAssignment>
<Facility ...>
      ...
</Facility>
</facilities>

In noticeAssignments this was done already. So at least the concept is not new.
<noticeAssignments>
<NoticeAssignment id="ch:1:NoticeAssignment:ch_1_ServiceJourney_33-15358-1-1_2_0" version="any" order="1">
            <validityConditions>
                   <AvailabilityConditionRef ref="ch:1:AvailabilityCondition:b8" version="any"/>
            </validityConditions>
            <NoticeRef ref="ch:1:Notice:I_04i" version="any"/>
</NoticeAssignment>
<NoticeAssignment ...>
      ...
</NoticeAssignment>
</noticeAssignments>

**Comment by Aurige** [comment]
For ServiceFacilitySet in Call, since the Call is a view grouping information about the SCHEDULED STOP POINT, SERVICE JOURNEY, POINT IN JOURNEY PATTERN... it would be ambiguous to what the ServiceFacilitySet applies

For the FacilityAssignment that you are proposing, I don't see any big objection in my side. We can also rework a bit the FacilitySetGroup to be able to reference a list of Facilities. I put this as a discussion point for next meeting.

**Comment by nick-knowles** [comment]
Can we clarify the actual requirement. - seemed to be several possible interpretations..

To have individual facilities on a SERVICE JOURNEY without wrapping in a FACILITY SET -   undesirable?

To reuse the  same FACILITY SET  on multiple SERVICE JOURNEYs - already possible (use a FacilitySetRef instead of a FacilitySet )

To reuse the  same FACILITY SET  on just some of the CALLs of a SERVICE JOURNEYs - ie for part of a journey - this in effect already possible (use a FACILITY SET on a JOURNEY PART)

To have an AVAILABILITY CONDITION on a   FACILITY SET - already possible, But note this can lead to contradictions if the condition conflicts with the scheduling of the journey

To allow multiple  FACILITY SETs to be associated with a SERVICE JOURNEY,  each with a different availability condition (eg restaurant  on weekdays , bar at weekends) . Not currently popssible. Could consider extension to allow a list of FACILITY SETs as a choice instead of a single one on a SERVICE JOURNEY (and elsewhere)

To reuse the   same   FACILITY SET  contents on multiple SERVICE JOURNEYS with a different  AVAILABILITY CONDITION in each usage case.  This is not currently possible - or desirable?

To allow SERVICE FACILITY SETs to be specified on individual CALLs  - informationally derived from FACILITY SETs on JOURNEY PARTS - potentially confusing?

**Comment by duexw** [comment]
Hi Nick, I think you summarized it correctly. This is what you can do already with the simple HRDF (HAFAS) model and it saves you from having the same FacilitySet 100 times just because it has different availability sets. Instead of having a facility set on each call, you could also have something like FromCallRef and ToCallRef, since the main use case is that the facility is only available on a section of the journey.

**Comment by Aurige** [comment]
_> allow multiple FACILITY SETs to be associated with a SERVICE JOURNEY, each with a different availability condition_

@Nick this looks to be already possible
![image](https://github.com/NeTEx-CEN/NeTEx/assets/3328999/0cefcee2-af15-4ae5-8a2c-0b1099d1d079)

and each ServiceFacilitySet has its own ValidityConditions .
What we "miss" is the ability to reuse the same set of facilities with different ValidityConditions

**Comment by Aurige** [comment]
and @ue71603 I still don't get what a FacilitySet on a Call would mean: let's say, as in your example, that the FacilitySet is just a Bar, would that mean that there is a Bar for the ServiceJourney, or just the JourneyPart, or et the StopPlace, or on the Quay, etc. The Call reference them all but will not target the FacilitySet.

This said, I agree that for now, the only way to say that "the bar is no longer operational on the last 4 stops" is to create a JourneyPart... which is not really convenient... we would need something like from StopPointInJP/Call to  StopPointInJP/Call, or above stop order number (note that the "above stop order number" is something that can be done with a ValidityContition having a ValidityRuleParameterGroup ...)

**Comment by Aurige** [comment]
Discussion: introduce a GroupOfFacilities (without AvailabilityConditions) that can be referenced by the FactilitySet => PR to be drafted @nick-knowles

**Comment by ue71603** [comment]
addressed in https://github.com/NeTEx-CEN/NeTEx/pull/731

**Comment by Aurige** [comment]
Documentation update will be managed in https://github.com/NeTEx-CEN/NeTEx/pull/731

**Comment by nick-knowles** [comment]
Wilfried undertook to code some XML .  Here is a model 

The new element is a FACILITY SET CALL ASSIGNMENT it has to go in Part2 as it references CALLs

Definition is: _The assignment of a FACILITY SET or SETs between two CALLs or other POINTs in PATTERN._ 

Note1: Provides a lightweight alternative to specifying FACILITY SETs on a JOURNEY PART.  
Note2: Precedence - It is assumed that the FACILITY SETs simply replace any existing FACILITY SETs specified for the or SERVICE  SERVICE JOURNEY (or SERVICE PART)., i.e. a complex merge of the facilities in the base and exception sets is not needed.   

![Image](https://github.com/user-attachments/assets/95afea61-f1fd-4712-8b82-8aff7e894ab6)


Note that this a specialisation of a simpler  FACILITY SET  ASSIGNMENT that can be placed in PART1 alongside FACILITY SET  that references just POINTS in PATTERN , not CALLs.

_"The assignment of a FACILITY SET showing an exception in a LINK SEQUENCE (such as a JOURNEY PATTERN, a COMMON SECTION, or a VEHICLE JOURNEY), possibly specifying at which POINT IN JOURNEY PATTERN the validity of the FACILITY starts and ends respectively"_




![Image](https://github.com/user-attachments/assets/780bd284-d185-41d8-b97b-6f0e852ffa71)
