### ISSUE TITLE
FlexibleOperation why not FlexibleModeOfOperation?

### ISSUE THREAD

**Issue by skinkie** [NeTEx-CEN/NeTEx#473]

**Comment by nick-knowles** [comment]
Element names are as as per spec . Structure names are as per convention of using noun (xxxxModeOfOperation) of superclass. SUgegst we leave as is

This is Transmodel UML

![image](https://github.com/NeTEx-CEN/NeTEx/assets/1826507/5896696b-17dc-4340-97a3-ac07e5b80c48)

This is NeTEx UML
![image](https://github.com/NeTEx-CEN/NeTEx/assets/1826507/19a6d1a0-00b8-439b-9345-4dfc6b3c6be0)

**Comment by ue71603** [comment]
@Aurige  @skinkie  I think Nick is right. We close it?

**Comment by skinkie** [comment]
No, I don't understand it.

**Comment by Aurige** [comment]
TM alignment

**Comment by skinkie** [comment]
It feels like it is it is not consistent with the other NeTEx concepts.

**Comment by nick-knowles** [comment]
It is consistent - although we generally add qualifiers to  the superclass name to arrive at the subclass name (POINT, TIMING POINT) , in a number of places  we specialise either  because the noun phrase gets too much of a mouthful (FLEXIBLE CONVENTIONAL MODE OF OPERATION aagh ) , or because the semantics become more focused    
Consider  the site hierarchy
    GROUP OF POINTS
        ZONE 
           PLACE 
               SITE ELEMENT,  
                   SITE,  
                     STOP PLACE, 
                     POINT OF INTEREST 
                     PARLING
                  SITE COMPONENT
                     STOP PLACE COMPONENT
 etc etc

**Comment by Aurige** [comment]
discussed
