### ISSUE TITLE
VAT Number next to CompanyNumber

### ISSUE THREAD

**Issue by skinkie** [NeTEx-CEN/NeTEx#481]
I think this is a sound request from @JohanEntur

**Comment by ue71603** [comment]
we can do that. The issue itself is a tat minimalistic.

**Comment by JohanEntur** [comment]
I feel like the problem is that there can be any number of "company numbers" since they'll be listed in different things for different countries. If there is only one field, you both have to leave it to the user to figure out which list the number is from, and even worse - if they are in two lists. Which number is listed in NeTEx?

Adding VAT as a separate field is nice since it's a global(ish) system, but as soon as one more number enters the picture we're here again.

Perhaps the most scalable way would be 
<companyNumbers>
and then specify all the necessary numbers with something that tells you the origin of the number, incl VAT which rightly should be called "VATIN" https://en.wikipedia.org/wiki/VAT_identification_number.

**Comment by Aurige** [comment]
I would refrain from trying to jump in the details of company identification ... that's a total nightmare at international level, with multiple registries, crazy links to customs, etc. 
This said, it can ba a good idea that, in EPIP, we recommand to use the EU-VAT number (when available) in CompanyNumber  
We can also ask what is the real use case behind...

**Comment by JohanEntur** [comment]
The background here is that we, as I've said on Basecamp, are building a database of organizations which we communicate with in order to establish a set of unique ID's. Basically the same principles as our national stops database.

In order to link them to judicially valid companies we use <CompanyNumber>. This works quite fine as long as we stay within Norway, but we have a small number of non-Norwegian companies, such as tavel agencies, and here we enter into the nightmare which @Aurige alludes to. So, do we just put any kind of company number into <CompanyNumber> or do we declare which system the number exists in?

I talked about VAT with Stefan because VAT is quite established, but I feel it needs to be specific. In fact, I feel the nightmare coming over me here :) Ideally it should be "CountryOfRegistration" with "CompanyNumber", and each country would have a unique number for their companies, but I'll just assume this is not even close to the case here.

So, either we do something clever here, or we follow @Aurige s suggestion of leaving everything out (or at least leave it to the keyValues 🐺🐺🐺), which I now suspect is far easier and has better cost-value.

😬

**Comment by skinkie** [comment]
VAT should be unique, Chamber of Commerce, DUNS etc. schemes are not. Hence the support would be in VAT.

**Comment by JohanEntur** [comment]
If anything can be made to work, I expect VAT is the one. :)
