### ISSUE TITLE
Too generic type for stop places in SiteFrame

### ISSUE THREAD

**Issue by vpaturet** [NeTEx-CEN/NeTEx#512]
The pull request introducing new modes (https://github.com/NeTEx-CEN/NeTEx/commit/147c902f0df0eee1e727acdba9eed392581d0170)
modified the type of stop places in a site frame from` StopPlace `to the more generic `StopPlace_` :

https://github.com/NeTEx-CEN/NeTEx/blob/3d1d9e716ffd2577a58b0a7b6bf9770ed5bf3276/xsd/netex_part_1/part1_ifopt/netex_ifopt_stopPlace_version.xsd#L113

where:
`<xsd:element ref="StopPlace" maxOccurs="unbounded"/>`
became:
`<xsd:element ref="StopPlace_" maxOccurs="unbounded"/>`

As a result, type checking is relaxed and it is now possible to refer to other types in SiteFrame/stopPlaces, such as:
```

<SiteFrame>
    <stopPlaces>
        <Parking/>
        <PointOfInterest/>
    </stopPlaces>
</SiteFrame>
```

These types have their own containers (`<parkings>,` `<pointOfInterests>`, ...) and should not be mixed with `<stopPlaces>`

We believe that this change was not intended and should be reverted.

**Comment by Aurige** [comment]
If I remember well, the triggering point here was that "New Modes" (vehicle pooling, vehicle sharing, etc.) sometimes need to define Stop Places (carpooling lines for example) that can then be Parkings, Car Pooling Areas or POIs ... but also Taxi Ranks (not for new modes, but some replacement lines, or some on demand services).

But I agree that in the SiteFrame that is not relevant since we already have <parkings>, <pointOfInterests>, ... and since stopPlacesInFrame_RelStructure is only used in SiteFrame, we should be able to revert this safely ...

@nick-knowles @ue71603 do you see any side effect from your current usages (accessibility or new modes) ?

**Comment by skinkie** [comment]
The change would fail https://github.com/NeTEx-CEN/NeTEx/blob/master/examples/functions/newModes/NewModes-CarPoolingExample.xml#L265

@Aurige is there any taxiRankInFrame forseen?

**Comment by Aurige** [comment]
not that I know !
I looked around, and I can't find a really easy solution (we are facing XLM inheritance limitation here: the inheritance linked between StopPlace and TaxiRank was initially designed to solve this, but for some reason it does not)

Adding a taxiRankInFrame would work, or allow StopPlaces and TaxiRank in stopPlacesInFrame_RelStructure (100% backward compatible and follows the initial intention) ... but that will only solve that case, and will not cover the generic VehicleMeeting Place .... we could add an xxxInFrame dedicated to _StopPlace, but it will overlap StopPlaceInFrame

Nothing I prefer to the current implementation in all these workarounds

**Comment by skinkie** [comment]
Lets discuss the 'why' first. Why are StopPlaces made generic to facilitate TaxiRank, is TaxiRank in Transmodel to be considered a StopPlace?

**Comment by skinkie** [comment]
Again, are they modelled in Transmodel in the same way?

**Comment by ue71603** [comment]
I have a problem there:
* Sharing is related to SITE not STOP PLACE also PARKING is more SITE than STOP PLACE
![image](https://github.com/NeTEx-CEN/NeTEx/assets/24227470/c2d40745-496d-4814-aeab-c165a92dc87c)

* VEHICLE MEETING POINT is NOT related to  STOP PLACE but to POINT
![image](https://github.com/NeTEx-CEN/NeTEx/assets/24227470/9ba2cc08-18d2-4baf-b45d-867a1767dae6)
![image](https://github.com/NeTEx-CEN/NeTEx/assets/24227470/7b09f051-0f8c-43d9-beb2-c4317f406b28)

* TAXI RANK is a STOP PLACE according to the definition. 
 
![image](https://github.com/NeTEx-CEN/NeTEx/assets/24227470/6194bb59-f7cb-472f-abd3-59dfeca60fd0)
But otherwise it has zero other connections in the model. 
The modelling of TAXI SERVICE PLACE ASSIGNMENT then would be wrong, because the equivalent in STOP PLACE can be assigned to a QUAY or STOP PLACE (TAXI RANK). Here it is only to the TAXI STAND
![image](https://github.com/NeTEx-CEN/NeTEx/assets/24227470/c929eeba-f581-4d6b-9a5a-5eb1935e02d9)
VEHICLE POOLING is then modeled differently, even when TAXI SERVICE is a specialisation of a POOLIING SERVICE:
![image](https://github.com/NeTEx-CEN/NeTEx/assets/24227470/4aad0b47-a50c-46c3-873e-9442f97129bd)

Also, in VEHICLE POOLING there are services with very clearly defined stops as you pointed out to me Christophe in an email earlier this week.

* Using STOP PLACE would not account for the dynamic versions of sharing and pooiling 

Even when a STOP PLACE is a SITE, the opposite is not true.

**Comment by Aurige** [comment]
Yes yes, I know ... no issue on the modelling side ! The question is only about explicit Frames and where to put the corresponding data. 
Up to now, all stops, pick-up and drop-off locations are available from the SiteFrame, under the  <StopPlaces> tag ... it could (should?) have been different, but that's the way it currently is. 
The proposed revert  will result in the fact that there is no more explicit Frame to host these objects... so we need to find a better way !

**Comment by ue71603** [comment]
@Aurige  What do we do with this one?

**Comment by ue71603** [comment]
fixed in https://github.com/NeTEx-CEN/NeTEx/pull/578

**Comment by skinkie** [comment]
> These types have their own containers (`<parkings>,` `<pointOfInterests>`, ...) and should not be mixed with `<stopPlaces>`

@vpaturet Parking and PointOfInterest has the substitution group 'Site', so you cannot do it under stopPlaces.
