### ISSUE TITLE
PassengerStopAssignment, how to to assure that it stays 1:N

### ISSUE THREAD

**Issue by skinkie** [NeTEx-CEN/NeTEx#660]
My assumption would be that the most specific case would be that one StopPlace or Quay should link to one or more different ScheduledStopPoints. When more than one StopPlaces (or Quays) are linked to the same ScheduledStopPoint that would stop making sense.

I understand that a ScheduledStopPoint could point to a StopPlace, and therefore more quays under it, for example the French railway situation, with dynamic quay assignment.

What are your thoughts on in?

**Comment by Aurige** [comment]
Yes having multiple StopPlaces  assigned to the same ScheduledStopPoint is not what is expected, but you are right the SNCF has this weird situation, either to assign to multiple Quays due to late assignment (they assign to all possible Quays), or even to assign to multiple StopPlaces because a train station is split in 2 (Hall 1 Quay A to N and Hall 2 Quay 5 to 23 in Gare de Lyon ...)

We also expect to have a StopPlace or Quay assigned to each ScheduledStopPoint but historically some operator had not description of the physical reality of the network and were staying at SSP level only (and we still have a few)

**Comment by ue71603** [comment]
@skinkie @Aurige so we don't assure it. Do we need a sentence in the schema telling about this in PassengerStopAssignment?

**Comment by Aurige** [comment]
PArt 1 was updated
