### ISSUE TITLE
ServiceJourney Origin/Destination and JourneyPart won't allow to start/end at a TimingPoint 

### ISSUE THREAD

**Issue by skinkie** [NeTEx-CEN/NeTEx#87]
At this moment ServiceJourney/Origin ServiceJourney/Destination and JourneyPart/FromStopPointRef JourneyPart/ToStopPointRef would not allow the use of a TimingPoint. A TimingPointInJourneyPattern can be the first and last stop in the JourneyPattern. I think the model fails here.

**Comment by Aurige** [comment]
A ScheduledStopPoint can also be a TimingPoint (cf TimingPointStatus attribut, etc.), therefore first and last stops can be timing points. If the TimingPoint is not a stop point, then it is not in hte ServiceJourneyPattern (restricted to ScheduledStopPoint), but in either in a higher level JouneyPattern, either in a more specialised TimingPattern.

**Comment by skinkie** [comment]
@Aurige it is certainly not restricted that way.

```
new ServiceJourneyPattern().withPointsInSequence(new PointsInJourneyPattern_RelStructure().withPointInJourneyPatternOrStopPointInJourneyPatternOrTimingPointInJourneyPattern())
```

**Comment by Aurige** [comment]
Yes sorry, the **ServiceJourneyPattern** is "_The JOURNEY PATTERN for a (passenger carrying) SERVICE JOURNEY._", but the **ServicePattern** is its "restriction" to ScheduledStopPoint. 
![image](https://user-images.githubusercontent.com/3328999/77937867-37db7e00-72b5-11ea-875d-45ea2045fa7c.png)
The definition of **ServicePattern**  is "_The subset of a JOURNEY PATTERN made up only of STOP POINTs IN JOURNEY PATTERN_"

**Comment by nick-knowles** [comment]
Note that  The origin and destination are 'Views' added by NeTEx - they do not exist in the normalised  Transmodel model.   They are are intended to provide convenient way of summarising the SERVICE JOURNEY (for PI purposes ) from the SERVICE PATTERN
Since by definition,  a SERVICE PATTERN can only contain SCHEDULED STOP POINTs,  the origin or destination of a SERVICE JOURNEY can only be a SCHEDULED STOP POINT, Christophe is Right,.

Why would a timing point (that isnt also a SCHEDULED STP POINT)   be of interest  to a passenger - it might be an arbitrary point in the middle of nowhere?

**Comment by janosu** [comment]
Hi Stefan,

Based on the above, your "JourneyPattern" should be divided into several parts, as the beginning and end do not include a travel service. These will to be a "DeadRun" patterns, while the remaining will have a "ServiceJourney", which is a travel service.

**Comment by ue71603** [comment]
Will comment how it is done with dead run..
